version: '3.1'

services:
  db:
    image: mysql:8.0.35-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docent
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./e2e/db:/docker-entrypoint-initdb.d
